### ISSUE TITLE
Update BEER code to deal with wordcloud for SOLR 4.8

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/adsabs#219]
We are currently getting the following error when querying the SOLR instance at http://54.173.87.140:8983/solr/collection1/select

```
ERROR 2014-12-16 12:44:06,132 app 28707 140054938552064 Exception on /visualization/word_cloud [POST]
Traceback (most recent call last):
  File "/proj.adsx/beer/python/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/proj.adsx/beer/python/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/proj.adsx/beer/python/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/proj.adsx/beer/python/lib/python2.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/proj.adsx/beer/python/lib/python2.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/proj.adsx/beer/adsabs/adsabs/modules/visualization/views.py", line 156, in word_cloud
    return render_template('word_cloud_embedded.html', wordcloud_data=wc_json(resp.raw_response()))
  File "/proj.adsx/beer/adsabs/adsabs/modules/visualization/solrjsontowordcloudjson.py", line 33, in wc_json
    tf_idf_info = list_to_dict(solr_json['termVectors'][2:])
KeyError: 'termVectors'
ERROR 2014-12-16 12:44:06,134 errors 28707 140054938552064 [error] 'termVectors', /visualization/word_cloud
```

**Comment by aaccomazzi** [comment]
Fixed with new montysolr release
