### ISSUE TITLE
Exception for papers without graphics in BEER

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/adsabs#230]
We currently get errors such as this one for some papers which seem to have zero graphics:
```
Exception on /abs/2008AJ....136..452G/ [GET]
Traceback (most recent call last):
  File "/proj.adsx/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/proj.adsx/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/proj.adsx/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/proj.adsx/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/proj.adsx/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/proj.adsx/beer/adsabs_gunicorn/adsabs/modules/abs/views.py", line 53, in abstract
    graphics = get_thumbnails(bibcode)
  File "/proj.adsx/beer/adsabs_gunicorn/adsabs/modules/graphics/paper_thumbnails.py", line 40, in get_thumbnails
    display_figure = random.choice(results['figures'])
  File "/proj.adsx/python/lib/python2.7/random.py", line 275, in choice
    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
IndexError: list index out of range
[error] list index out of range, /abs/2008AJ....136..452G/
```

**Comment by ehenneken** [comment]
Fixed
